name: qrden
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  provider: ^6.1.5+1
  mobile_scanner: ^7.1.2
  cloud_firestore: ^6.0.2
  google_fonts: ^6.3.2
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  firebase_storage: ^13.0.2
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  path_provider: ^2.1.5
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
